[project]
name = "transcode"
version = "0.0.dev"
description = "This will be a transcoding script for video containers"
authors = [ { name = "Justin Herndon", email = "jherndon111@gmail.com" } ]
maintainers = [ { name = "Justin Herndon", email = "jherndon111@gmail.com" } ]
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = ["cli"]
dependencies = [
    "click",
    "python-ffmpeg>=2.0.12",
]

[dependency-groups]
dev = [
  "ruff",
  "pytest",
]

[project.scripts]
transcode = "transcode.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.ruff]
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["UP", "D", "I", "B", "SIM", "S"]
